# Common tags applied to all resources
tags:
  DevOpsDeploy: BaselineConfig
  team: DevOps

name: BaselineConfig

network:
  vpc:
    natGatewaySubnetName: Public
    maxAzs: 1

  subnets:
    # Backend subnet
    - cidrMask: 22
      name: Private
      subnetType: PRIVATE
    # Data subnet
    - cidrMask: 22
      name: Data
      subnetType: PRIVATE
    # Public subnet
    - cidrMask: 22
      name: Public
      subnetType: PUBLIC

compute:
  eks:
    eksOptimizedImage: STANDARD
    version: "1.18"
    nodeGroup:
      name: NodeGroup01
      instanceType: t3.medium
      maxCapacity: 3
      minCapacity: 1
      desiredCapacity: 1
      subnetGroupName: Private
    subnetGroupNames:
      - Private
      - Public

data:
  elasticsearch:
    domainName: BaselineConfig
    version: "7.9"
    capacity:
      masterNodes:
        instanceType: m5.large.elasticsearch
        count: 3
      dataNodes:
        instanceType: c5.xlarge.elasticsearch
        count: 3
    ebs:
      volumeSize: 32
    zoneAwareness:
      enabled: true
      count: 3
    subnetGroupName: Data
    logging:
      appLogEnabled: true
      auditLogEnabled: true
      slowIndexLogEnabled: true
      slowIearchLogEnabled: true
