awsAccount: "277820706013"
awsRegion: eu-west-3

network:
  vpc:
    cidr: 10.9.0.0/18

data:
  elasticsearch:
    capacity:
      masterNodes:
        instanceType: t2.small.elasticsearch
        count: 3
      dataNodes:
        instanceType: t2.small.elasticsearch
        count: 3
    ebs:
      volumeSize: 10
    zoneAwareness:
      enabled: true
      count: 3
    logging:
      appLogEnabled: false
      auditLogEnabled: false
      slowIndexLogEnabled: false
      slowIearchLogEnabled: false
